name: Manifest Download

on:
  schedule:
    - cron: '0 */1 * * *'  # 每小时触发一次工作流

  workflow_dispatch:
    inputs:
      account-concurrency:
        description: 'Account concurrency'
        required: true
        default: 8
        type: number

      manifest-concurrency:
        description: 'Manifest concurrency'
        required: true
        default: 8
        type: number

concurrency:
  group: download
  cancel-in-progress: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: true
          fetch-depth: 0
          fetch-tags: true

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true

      - name: Restore serverlist
        uses: actions/cache/restore@v4
        with:
          path: servers.bin
          key: ${{ runner.os }}-servers-
          restore-keys: ${{ runner.os }}-servers-

      - name: Restore previous build
        uses: actions/cache@v4
        id: binaries
        with:
          path: |
            bin/
            obj/
          key: ${{ runner.os }}-bin-${{ github.sha }}

      - name: Build manifest downloader
        if: steps.binaries.outputs.cache-hit != 'true'
        run: dotnet build --configuration Release

      - name: Download manifest
        # 传递 --account 参数，指定 accounts.json 文件路径
        run: dotnet run --no-build --configuration Release -- download -t ${{ secrets.GITHUB_TOKEN }} -c ${{ github.event.inputs.account-concurrency || 32 }} -p ${{ github.event.inputs.manifest-concurrency || 8 }} -k ${{ secrets.AES_KEY }} --account accounts.json

      - name: Save serverlist
        uses: actions/cache/save@v4
        with:
          path: servers.bin
          key: ${{ runner.os }}-servers-${{ hashFiles('servers.bin') }}
